name: Java Unit Test CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download JUnit Platform
        run: |
          curl -L -o junit-platform-console-standalone.jar \
          https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.10.1/junit-platform-console-standalone-1.10.1.jar

      - name: Compile
      
        run: |
          javac -cp .:junit-platform-console-standalone.jar cal.java calTest.java

      - name: Run Unit Tests
        run: |
          java -jar junit-platform-console-standalone.jar \
          --class-path . \
          --scan-class-path
